const MITT_EVENTS = {
    CLICK_TO_SERVICE_BUTTON: 'CLICK_TO_SERVICE_BUTTON',
    CLICK_TO_CONTACT_BUTTON: 'CLICK_TO_CONTACT_BUTTON',
    CLICK_TO_SERVICE_HOME: 'CLICK_TO_SERVICE_HOME',
}

export {
    MITT_EVENTS,
}
